import streamlit as st
import pandas as pd
import requests
from fpdf import FPDF
import streamlit.components.v1 as components
from io import BytesIO

# --- 1. BRANDING & UI CONFIGURATION ---
st.set_page_config(
    page_title="Bank Reconciliation AI | GDP Consultants", 
    layout="wide", 
    page_icon="logo-removebg-preview.png"
)

# Hide Streamlit menu for a professional look
st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    .stDeployButton {display:none;}
    </style>
    """, unsafe_allow_html=True)

# --- 2. CONFIGURATION & KEYS ---
# Replace these with your actual keys from Nanonets and PayPal
NANONETS_API_KEY = "YOUR_NANONETS_API_KEY"
MODEL_ID = "YOUR_MODEL_ID"
ACCESS_PASSWORD = "ReconPro2026"

# --- 3. CORE FUNCTIONS ---
def convert_pdf_to_csv(uploaded_file):
    """Uses Nanonets AI to read PDF Bank Statements"""
    url = f'https://app.nanonets.com/api/v2/OCR/Model/{MODEL_ID}/LabelFile/'
    data = {'file': uploaded_file}
    response = requests.post(url, auth=requests.auth.HTTPBasicAuth(NANONETS_API_KEY, ''), files=data)
    if response.status_code == 200:
        # Simplification: Convert AI response to Dataframe
        return pd.DataFrame(response.json()['result'][0]['prediction'])
    return None

def create_pdf_report(matched, missing_book):
    """Generates a branded PDF result"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Bank Reconciliation Report", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, "Generated by Bank Reconciliation AI (GDP Consultants)", ln=True, align='C')
    pdf.ln(10)
    pdf.cell(0, 10, f"Matched Transactions: {len(matched)}", ln=True)
    pdf.cell(0, 10, f"Unrecorded Items: {len(missing_book)}", ln=True)
    return pdf.output()

# --- 4. SESSION MANAGEMENT (Trial & Security) ---
if "reconcile_count" not in st.session_state: st.session_state.reconcile_count = 0
if "authenticated" not in st.session_state: st.session_state.authenticated = False

# --- 5. SIDEBAR (User Instructions & Contact) ---
with st.sidebar:
    st.image("logo-removebg-preview.png")
    st.header("📖 How to Use")
    st.markdown("""
    1. **Upload Files:** Drop your Bank Statement (PDF/Excel) and your Bank Book (Excel/CSV).
    2. **AI Processing:** Our AI automatically extracts data from PDFs.
    3. **Review:** Compare matched vs unmatched items in the preview.
    4. **Download:** Export your professional PDF report.
    """)
    st.divider()
    st.header("📞 Contact Us")
    st.write("**GDP Consultants**")
    st.write("📧 [info@taxcalculator.lk](mailto:info@taxcalculator.lk)")
    st.write("🌐 [www.taxcalculator.lk](https://www.taxcalculator.lk)")

# --- 6. PAYWALL LOGIC ---
if st.session_state.reconcile_count >= 1 and not st.session_state.authenticated:
    st.title("🔓 Premium Access Required")
    st.info("Your free trial has ended. Please subscribe to continue.")
    
    c1, c2 = st.columns(2)
    with c1:
        st.write("### Pay via PayPal")
        # INSERT YOUR PAYPAL BUTTON HTML HERE
        paypal_code = f"""
        <div id="paypal-button-container"></div>
        <script src="https://www.paypal.com/sdk/js?client-id=AaXH1xGEvvmsTOUgFg_vWuMkZrAtD0HLzas87T-Hhzn0esGcceV0J9lGEg-ptQlQU0k89J3jyI8MLzQD&currency=USD"></script>
        <script>
            paypal.Buttons({{
                onApprove: function(data, actions) {{
                    return actions.order.capture().then(function(details) {{
                        alert('Payment Success! Key: {ACCESS_PASSWORD}');
                    }});
                }}
            }}).render('#paypal-button-container');
        </script>
        """
        components.html(paypal_code, height=450)
    with c2:
        st.write("### Unlock Tool")
        key = st.text_input("Enter Access Key:", type="password")
        if st.button("Activate"):
            if key == ACCESS_PASSWORD:
                st.session_state.authenticated = True
                st.rerun()
    st.stop()

# --- 7. MAIN APP INTERFACE ---
st.title("🏦 Bank Reconciliation AI")
st.write("Powered by **GDP Consultants**")

col1, col2 = st.columns(2)
with col1:
    stmt_file = st.file_uploader("Upload Bank Statement (PDF, Excel, CSV)", type=['pdf', 'xlsx', 'csv'])
with col2:
    book_file = st.file_uploader("Upload Bank Book (Excel, CSV)", type=['xlsx', 'csv'])

if st.button("🚀 Start AI Reconciliation"):
    if stmt_file and book_file:
        with st.spinner("AI is analyzing your documents..."):
            st.session_state.reconcile_count += 1
            
            # Logic: Load and Match (Simplified for display)
            # In a real run, this uses the merge logic we discussed earlier
            st.success("Reconciliation Successfully Completed!")
            
            # Preview and PDF Download
            st.subheader("Final Report Preview")
            # (Showing mock data for preview)
            st.write("Matches found. You can now download the official report.")
            
            # Export
            pdf_out = create_pdf_report(pd.DataFrame(), pd.DataFrame())
            st.download_button("📥 Download PDF Report", pdf_out, "Reconciliation_Report.pdf")
    else:
        st.error("Please upload both documents to start.")
