import streamlit as st
import pandas as pd
import requests
from fpdf import FPDF
import streamlit.components.v1 as components
from io import BytesIO

# --- 1. BRANDING & UI CONFIGURATION ---
st.set_page_config(
    page_title="Bank Reconciliation AI | GDP Consultants", 
    layout="wide", 
    page_icon="logo-removebg-preview.png"
)

# Hide Streamlit specific UI elements
st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    .stDeployButton {display:none;}
    </style>
    """, unsafe_allow_html=True)

# --- 2. CONFIGURATION ---
ACCESS_PASSWORD = "ReconPro2026"
# (Keep your Nanonets Keys here)
NANONETS_API_KEY = "YOUR_NANONETS_API_KEY"
MODEL_ID = "YOUR_MODEL_ID"

# --- 3. UPDATED PDF FUNCTION (FIXED ERROR) ---
def create_pdf_report(matched_count, missing_count):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Bank Reconciliation Report", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, "Generated by Bank Reconciliation AI (GDP Consultants)", ln=True, align='C')
    pdf.ln(10)
    pdf.cell(0, 10, f"Matched Transactions: {matched_count}", ln=True)
    pdf.cell(0, 10, f"Unrecorded Items: {missing_count}", ln=True)
    
    # Crucial Fix: Return as bytes
    return bytes(pdf.output())

# --- 4. SESSION & AUTH ---
if "reconcile_count" not in st.session_state: st.session_state.reconcile_count = 0
if "authenticated" not in st.session_state: st.session_state.authenticated = False

# --- 5. SIDEBAR ---
with st.sidebar:
    # Try to load logo if it exists
    try:
        st.image("logo-removebg-preview.png")
    except:
        pass
    st.header("📖 How to Use")
    st.markdown("""
    1. **Upload Files:** Upload Bank Statement (PDF/Excel) and Bank Book (Excel/CSV).
    2. **AI Processing:** Our AI extracts data automatically from PDFs.
    3. **Review:** Check matched/unmatched items.
    4. **Download:** Export your final PDF report.
    """)
    st.divider()
    st.header("📞 Contact Us")
    st.write("**GDP Consultants**")
    st.write("📧 info@taxcalculator.lk")
    st.write("🌐 www.taxcalculator.lk")

# --- 6. PAYWALL LOGIC ---
if st.session_state.reconcile_count >= 1 and not st.session_state.authenticated:
    st.title("🔓 Premium Access Required")
    st.info("Your free trial has ended. Please subscribe to continue.")
    c1, c2 = st.columns(2)
    with c1:
        paypal_code = f"""
        <div id="paypal-button-container"></div>
        <script src="https://www.paypal.com/sdk/js?client-id=AaXH1xGEvvmsTOUgFg_vWuMkZrAtD0HLzas87T-Hhzn0esGcceV0J9lGEg-ptQlQU0k89J3jyI8MLzQD&currency=USD"></script>
        <script>
            paypal.Buttons({{
                onApprove: function(data, actions) {{
                    return actions.order.capture().then(function(details) {{
                        alert('Payment Success! Use Key: {ACCESS_PASSWORD}');
                    }});
                }}
            }}).render('#paypal-button-container');
        </script>
        """
        components.html(paypal_code, height=450)
    with c2:
        key = st.text_input("Enter Access Key:", type="password")
        if st.button("Activate"):
            if key == ACCESS_PASSWORD:
                st.session_state.authenticated = True
                st.rerun()
    st.stop()

# --- 7. MAIN INTERFACE ---
st.title("Bank Reconciliation AI")
st.write("Powered by **GDP Consultants**")

col1, col2 = st.columns(2)
with col1:
    stmt_file = st.file_uploader("Bank Statement", type=['pdf', 'xlsx', 'csv'])
with col2:
    book_file = st.file_uploader("Bank Book", type=['xlsx', 'csv'])

if st.button("🚀 Run AI Reconciliation"):
    if stmt_file and book_file:
        with st.spinner("Analyzing..."):
            # Update counter
            st.session_state.reconcile_count += 1
            
            # (Processing Logic here...)
            m_count = 10 # Example data
            u_count = 2  # Example data
            
            st.success("Reconciliation Successfully Completed!")
            
            # PDF Generation with the fix
            pdf_bytes = create_pdf_report(m_count, u_count)
            
            st.download_button(
                label="📥 Download PDF Report",
                data=pdf_bytes,
                file_name="Reconciliation_Report.pdf",
                mime="application/pdf"
            )
    else:
        st.error("Please upload both documents.")
